
COMPILER=g++
INCLUDE=../../include/tools/stringtokenizer/

test: 
	@echo "To test, enter test <params>"
	$(COMPILER) -g -I$(INCLUDE) -combine StringTokenizer.cpp Test.cpp -o test

clean:
	@rm test

.PHONY: test clean
